### ISSUE TITLE
Error on Ubuntu 15.10 - gawk 4.1.1

### ISSUE THREAD

**Issue by ghost** [TheMozg/awk-raycaster#15]
$ gawk -f awkaster.awk 
gawk: awkaster.awk:5: <!DOCTYPE html>
gawk: awkaster.awk:5: ^ syntax error
gawk: awkaster.awk:6: <!DOCTYPE html>
gawk: awkaster.awk:6:                ^ unexpected newline or end of string
gawk: awkaster.awk:8:     <meta charset='utf-8'>
gawk: awkaster.awk:8:                   ^ invalid char ''' in expression

**Comment by TheMozg** [comment]
Make sure you download the actual `.awk` file instead of the webpage
