### ISSUE TITLE
How to port this game on Android?

### ISSUE THREAD

**Issue by Alihusejn** [TheMozg/awk-raycaster#18]

**Comment by TheMozg** [comment]
On Android it's possible to install terminal emulator app and run gawk in Linux environment. A custom terminal emulator with preinstalled gawk and usable controls is one way to do it.

Or just rewrite in Java.

**Comment by sleeptightAnsiC** [comment]
It works just fine under Termux these days

<details><summary>screenshot</summary>
<p>

![Screenshot_20251009_211648_com.termux.jpg](https://github.com/user-attachments/assets/acba4c2b-c13f-4ae4-b494-deefacb3740c)

</p>
</details>
