### ISSUE TITLE
if using gawk features, it no longer is an awk program

### ISSUE THREAD

**Issue by drawkula** [TheMozg/awk-raycaster#19]
`gawk` is a superset if `awk`, so a program using `gawk` features nis not longer an `awk` program.

Please change the repo title from

>Pseudo-3D shooter written completely in awk using raycasting technique

to

> Pseudo-3D shooter written completely in gawk using raycasting technique

for exactness.

**Comment by ailrk** [comment]
gawk is GNU implementation of awk, nothing wrong I guess.

**Comment by drawkula** [comment]
GAWK is a superset of AWK and standard AWK will not run this program.

So I guess explicitly naming it a "GAWK program" is the only correct choice.

**Comment by TheMozg** [comment]
Updated description.
