### ISSUE TITLE
Rendering/display speedup suggestion

### ISSUE THREAD

**Issue by i336** [TheMozg/awk-raycaster#5]
```
function redraw() {
  str = "\033[1;1H"
  ...
```

The above sends the cursor to the top-right of the terminal without clearing it.

FWIW, I like the scroll-to-redraw effect - it's kinda reminiscent of a bouncy CRT - but the above change results in _much_ less work for old/dumb terminals like `xterm`, making the whole thing a lot faster ( and decreasing dizziness by 100% everywhere :D).

An overview on escape sequences can be found in `man console_codes` (Linux manpages-specific); a more in-depth analysis can be found in [dtterm(5)](http://www2.phys.canterbury.ac.nz/dept/docs/manuals/unix/DEC_4.0e_Docs/HTML/MAN/MAN5/0036____.HTM), an absolutely ancient doc but the most comprehensive I've yet found (test what you read _everywhere_ before trusting it tho).

The escape sequence listed above is practically standard and I would be very gobsmacked if you ever got an incompatibility report on it.

Also - this thing is awesome and I'll definitely be studying it at some point, awk seriously FTW! :D
(And kudos for making this tidbit such an easy fix!)

**Comment by ghost** [comment]
Just saw this comment after making a pull request.

**Comment by TheMozg** [comment]
Thanks for suggestion - `xterm` rendering is now blazingly fast. I have also used `\033[J` escape sequence to clear everything _else_ on the screen in case there are leftover lines form last frame.

SHA: 5fb40ec71b4ab87a187b8eee4f764d0f365bf15b
