### ISSUE TITLE
Option to change WASD to ZQSD

### ISSUE THREAD

**Issue by Haroenv** [TheMozg/awk-raycaster#8]
Or a more arbitrary change to set your own moving characters would be optimal if you have a not-qwerty-layout.

**Comment by khalidchawtany** [comment]
You can change the hard-coded keys in the following lines:
501
504
519
521

I prefer vim's **hjkl** keys.

**Comment by pporada-gl** [comment]
Can we get a config file to set the keybindings?

**Comment by TheMozg** [comment]
Moved key bindings to the `#INITIALIZATION` section. You may change them easily.

SHA: 340313177523b29402786ffb55412273e7134eb0
